services:
  - type: web
    name: employee-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_mongodb:app
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    disk:
      name: employee-data
      mountPath: /data
      sizeGB: 1
